### ISSUE TITLE
Question: Should the published docker image contain a pre-built instance of DSpace?

### ISSUE THREAD

**Issue by terrywbrady** [DSpace-Labs/DSpace-Docker-Images#5]
If so, I would imagine that we would build and re-publish images each time that there is a major DSpace release.

Once a user has deployed a container, the user would have the option to re-deploy the code within the container.

**Comment by pnbecker** [comment]
I think it would be great to have docker images containing pre-built instances of all official DSpace-Releaes. The question is, if we can automate this so far, that building and pushing these images could be done within the maven release process?

**Comment by pnbecker** [comment]
@terrywbrady just mentioned the idea to use Travis to build images for every major branch (master, dspace-6_x, ...). I like that idea!

**Comment by pnbecker** [comment]
@terrywbrady and me agreed on the following:
 - We will publish pre-complied images for all actual DSpace Releases (DSpace 4, 5, and 6) manually.
 - We want to work on automating this with the maven release plugin. This has to be agreed by the other committers as it would make Docker a requirement to release DSpace.
 - We will create pre-compiled images for all our branches as soon as we got travis to do this for us. We won't build and publish these images manually.

**Comment by pnbecker** [comment]
If we want Travis CI to push images, we will have to add some kind of credentials to our Travis environment, so that Travis can authenticate to docker hub. Within [Travis' documentation](https://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry) they describe how to add the credentials to environment variables and mention that those can be encrypted. We have to check this out.
